from dragonfly import routes

routes.get('', 'PageController@index')
routes.resource('articles', 'ArticleController')
routes.post('articles/<id:int>/comments', 'CommentController@store')
routes.delete('comments/<id:int>', 'CommentController@destroy')
routes.get('users/<id:int>', 'UserController@show')

# Auth routes (generated by the 'auth' command)
routes.get('login', 'UserController@login')
routes.get('register', 'UserController@register')

routes.post('login', 'UserController@authenticate')
routes.post('register', 'UserController@store')
routes.post('logout', 'UserController@deauthenticate')
